# generated by datamodel-codegen:
#   filename:  datacite-4.6.yaml
#   timestamp: 2026-09-26T10:45:44+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Identifier(BaseModel):
    """
    The Identifier is a unique string that identifies a resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier_type: Annotated[str, Field(alias="identifierType")] = "DOI"
    identifier: str


class NameIdentifier(BaseModel):
    """
    Uniquely identifies an individual or legal entity, according to various schemes.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name_identifier: Annotated[str | None, Field(alias="nameIdentifier")] = None
    """
    Uniquely identifies an individual or legal entity, according to various schemes.
    """
    name_identifier_scheme: Annotated[str, Field(alias="nameIdentifierScheme")]
    """
    The name of the name identifier scheme.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the name identifier scheme.
    """


class Affiliation(BaseModel):
    """
    The organizational or institutional affiliation of the creator.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    affiliation_identifier: Annotated[str | None, Field(alias="affiliationIdentifier")] = None
    """
    Uniquely identifies the organizational affiliation of the creator.
    """
    affiliation_identifier_scheme: Annotated[
        str | None, Field(alias="affiliationIdentifierScheme")
    ] = None
    """
    The name of the affiliation identifier scheme
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the affiliation identifier scheme.
    """


class NameType(Enum):
    """
    The type of name.
    """

    ORGANIZATIONAL = "Organizational"
    PERSONAL = "Personal"


class Creator(BaseModel):
    """
    The main researcher involved in producing the data, or the author of the publication.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str
    """
    The full name of the creator.
    """
    name_type: Annotated[NameType | None, Field(alias="nameType")] = None
    given_name: Annotated[str | None, Field(alias="givenName")] = None
    """
    The personal or first name of the creator.
    """
    family_name: Annotated[str | None, Field(alias="familyName")] = None
    """
    The surname or last name of the creator.
    """
    name_identifiers: Annotated[list[NameIdentifier] | None, Field(alias="nameIdentifiers")] = None
    """
    Uniquely identifies an individual or legal entity, according to various schemes.
    """
    affiliation: list[Affiliation] | None = None
    """
    The organizational or institutional affiliations of the creator.
    """


class TitleType(Enum):
    """
    The type of Title (other than the Main Title).
    """

    ALTERNATIVE_TITLE = "AlternativeTitle"
    SUBTITLE = "Subtitle"
    TRANSLATED_TITLE = "TranslatedTitle"
    OTHER = "Other"


class Title(BaseModel):
    """
    A name or title by which a resource is known. May be the title of a dataset or the name of a piece of software or an instrument.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    title: str
    """
    A name or title by which a resource is known
    """
    lang: str | None = None
    """
    The languages of the title.
    """
    title_type: Annotated[TitleType | None, Field(alias="titleType")] = None
    """
    The type of Title (other than the Main Title).
    """


class Publisher(BaseModel):
    """
    The name of the entity that holds, archives, publishes, prints, distributes, releases, issues, or produces the resource. This property will be used to formulate the citation, so consider the prominence of the role.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str
    """
    The name of the entity that holds, archives, publishes, prints, distributes, releases, issues, or produces the resource. This property will be used to formulate the citation, so consider the prominence of the role.
    """
    publisher_identifier: Annotated[str | None, Field(alias="publisherIdentifier")] = None
    """
    Uniquely identifies the publisher, according to various schemes.
    """
    publisher_identifier_scheme: Annotated[str | None, Field(alias="publisherIdentifierScheme")] = (
        None
    )
    """
    The name of the publisher identifier scheme.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the publisher identifier scheme.
    """
    lang: str | None = None
    """
    The language used by the Publisher.
    """


class Subject(BaseModel):
    """
    Subject, keyword, classification code, or key phrase describing the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    subject: str
    """
    Subject, keyword, classification code, or key phrase describing the resource.
    """
    subject_scheme: Annotated[str | None, Field(alias="subjectScheme")] = None
    """
    The name of the subject scheme or classification code or authority if one is used.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the subject identifier scheme.
    """
    value_uri: Annotated[AnyUrl | None, Field(alias="valueURI")] = None
    """
    The URI of the subject term.
    """
    classification_code: Annotated[str | None, Field(alias="classificationCode")] = None
    """
    The classification code used for the subject term in the subject schemes.
    """
    lang: str | None = None
    """
    The language used in the Subject.
    """


class ContributorType(Enum):
    """
    The type of contributor of the resource
    """

    CONTACT_PERSON = "ContactPerson"
    DATA_COLLECTOR = "DataCollector"
    DATA_CURATOR = "DataCurator"
    DATA_MANAGER = "DataManager"
    DISTRIBUTOR = "Distributor"
    EDITOR = "Editor"
    HOSTING_INSTITUTION = "HostingInstitution"
    PRODUCER = "Producer"
    PROJECT_LEADER = "ProjectLeader"
    PROJECT_MANAGER = "ProjectManager"
    PROJECT_MEMBER = "ProjectMember"
    REGISTRATION_AGENCY = "RegistrationAgency"
    REGISTRATION_AUTHORITY = "RegistrationAuthority"
    RELATED_PERSON = "RelatedPerson"
    RESEARCHER = "Researcher"
    RESEARCH_GROUP = "ResearchGroup"
    RIGHTS_HOLDER = "RightsHolder"
    SPONSOR = "Sponsor"
    SUPERVISOR = "Supervisor"
    TRANSLATOR = "Translator"
    WORK_PACKAGE_LEADER = "WorkPackageLeader"
    OTHER = "Other"


class Contributor(Creator):
    """
    The institution or person responsible for collecting, managing, distributing, or otherwise contributing to the development of the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    contributor_type: Annotated[ContributorType, Field(alias="contributorType")]


class DateType(Enum):
    """
    The type of date
    """

    ACCEPTED = "Accepted"
    AVAILABLE = "Available"
    COPYRIGHTED = "Copyrighted"
    COLLECTED = "Collected"
    COVERAGE = "Coverage"
    CREATED = "Created"
    ISSUED = "Issued"
    SUBMITTED = "Submitted"
    UPDATED = "Updated"
    VALID = "Valid"
    WITHDRAWN = "Withdrawn"
    OTHER = "Other"


class Date(BaseModel):
    """
    Date relevant to the work.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    date: date_aliased
    """
    Date relevant to the work.
    """
    date_type: Annotated[DateType, Field(alias="dateType")]
    """
    The type of date
    """
    date_information: Annotated[str | None, Field(alias="dateInformation")] = None
    """
    Specific information about the date, if appropriate.
    """


class ResourceTypeGeneral(Enum):
    """
    The general type of a resource.
    """

    AUDIOVISUAL = "Audiovisual"
    AWARD = "Award"
    BOOK = "Book"
    BOOK_CHAPTER = "BookChapter"
    COLLECTION = "Collection"
    COMPUTATIONAL_NOTEBOOK = "ComputationalNotebook"
    CONFERENCE_PAPER = "ConferencePaper"
    CONFERENCE_PROCEEDING = "ConferenceProceeding"
    DATA_PAPER = "DataPaper"
    DATASET = "Dataset"
    DISSERTATION = "Dissertation"
    EVENT = "Event"
    IMAGE = "Image"
    INTERACTIVE_RESOURCE = "InteractiveResource"
    INSTRUMENT = "Instrument"
    JOURNAL = "Journal"
    JOURNAL_ARTICLE = "JournalArticle"
    MODEL = "Model"
    OUTPUT_MANAGEMENT_PLAN = "OutputManagementPlan"
    PEER_REVIEW = "PeerReview"
    PHYSICAL_OBJECT = "PhysicalObject"
    PREPRINT = "Preprint"
    PROJECT = "Project"
    REPORT = "Report"
    SERVICE = "Service"
    SOFTWARE = "Software"
    SOUND = "Sound"
    STANDARD = "Standard"
    STUDY_REGISTRATION = "StudyRegistration"
    TEXT = "Text"
    WORKFLOW = "Workflow"
    OTHER = "Other"


class ResourceType(BaseModel):
    """
    A description of the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    resource_type: Annotated[str, Field(alias="resourceType")]
    """
    A description of the resource.
    """
    resource_type_general: Annotated[ResourceTypeGeneral, Field(alias="resourceTypeGeneral")]


class AlternateIdentifier(BaseModel):
    """
    An identifier other than the primary Identifier applied to the resource being registered.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    alternate_identifier: Annotated[str | None, Field(alias="alternateIdentifier")] = None
    """
    An identifier other than the primary Identifier applied to the resource being registered
    """
    alternate_identifier_type: Annotated[
        ResourceTypeGeneral, Field(alias="alternateIdentifierType")
    ]


class RelationType(Enum):
    """
    Description of the relationship of the resource being registered (A) and the related resource (B).
    """

    IS_CITED_BY = "IsCitedBy"
    CITES = "Cites"
    IS_SUPPLEMENT_TO = "IsSupplementTo"
    IS_SUPPLEMENTED_BY = "IsSupplementedBy"
    IS_CONTINUED_BY = "IsContinuedBy"
    CONTINUES = "Continues"
    IS_DESCRIBED_BY = "IsDescribedBy"
    DESCRIBES = "Describes"
    HAS_METADATA = "HasMetadata"
    IS_METADATA_FOR = "IsMetadataFor"
    HAS_VERSION = "HasVersion"
    IS_VERSION_OF = "IsVersionOf"
    IS_NEW_VERSION_OF = "IsNewVersionOf"
    IS_PREVIOUS_VERSION_OF = "IsPreviousVersionOf"
    IS_PART_OF = "IsPartOf"
    HAS_PART = "HasPart"
    IS_PUBLISHED_IN = "IsPublishedIn"
    IS_REFERENCED_BY = "IsReferencedBy"
    REFERENCES = "References"
    IS_DOCUMENTED_BY = "IsDocumentedBy"
    DOCUMENTS = "Documents"
    IS_COMPILED_BY = "IsCompiledBy"
    COMPILES = "Compiles"
    IS_VARIANT_FORM_OF = "IsVariantFormOf"
    IS_ORIGINAL_FORM_OF = "IsOriginalFormOf"
    IS_IDENTICAL_TO = "IsIdenticalTo"
    IS_REVIEWED_BY = "IsReviewedBy"
    REVIEWS = "Reviews"
    IS_DERIVED_FROM = "IsDerivedFrom"
    IS_SOURCE_OF = "IsSourceOf"
    IS_REQUIRED_BY = "IsRequiredBy"
    REQUIRES = "Requires"
    IS_OBSOLETED_BY = "IsObsoletedBy"
    OBSOLETES = "Obsoletes"
    IS_COLLECTED_BY = "IsCollectedBy"
    COLLECTS = "Collects"
    IS_TRANSLATION_OF = "IsTranslationOf"
    HAS_TRANSLATION = "HasTranslation"


class RelatedIdentifierType(Enum):
    """
    The type of the RelatedIdentifier.
    """

    ARK = "ARK"
    AR_XIV = "arXiv"
    BIBCODE = "bibcode"
    CSTR = "CSTR"
    DOI = "DOI"
    EAN13 = "EAN13"
    EISSN = "EISSN"
    HANDLE = "Handle"
    IGSN = "IGSN"
    ISBN = "ISBN"
    ISSN = "ISSN"
    ISTC = "ISTC"
    LISSN = "LISSN"
    LSID = "LSID"
    PMID = "PMID"
    PURL = "PURL"
    RRID = "RRID"
    UPC = "UPC"
    URL = "URL"
    URN = "URN"
    W3ID = "w3id"


class RelatedIdentifier(BaseModel):
    """
    Identifier of related resources.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    related_identifier: Annotated[str | None, Field(alias="relatedIdentifier")] = None
    """
    Identifier of related resources.
    """
    related_identifier_type: Annotated[
        RelatedIdentifierType | None, Field(alias="relatedIdentifierType")
    ] = None
    relation_type: Annotated[RelationType | None, Field(alias="relationType")] = None
    related_metadata_scheme: Annotated[str | None, Field(alias="relatedMetadataScheme")] = None
    """
    The name of the schemes.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the name identifier scheme.
    """
    scheme_type: Annotated[str | None, Field(alias="schemeType")] = None
    """
    The type of the relatedMetadataScheme, linked with the schemeURI
    """
    resource_type_general: Annotated[
        ResourceTypeGeneral | None, Field(alias="resourceTypeGeneral")
    ] = None


class Right(BaseModel):
    """
    Any right information for this resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rights: str
    """
    Any right information for this resource.
    """
    rights_uri: Annotated[AnyUrl | None, Field(alias="rightsURI")] = None
    """
    The URI of the license.
    """
    rights_identifier: Annotated[str | None, Field(alias="rightsIdentifier")] = None
    """
    A short, standardized version of the license name.
    """
    rights_identifier_scheme: Annotated[str | None, Field(alias="rightsIdentifierScheme")] = None
    """
    The name of the scheme.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the rightsIdentifierScheme.
    """


class DescriptionType(Enum):
    """
    The type of the Description.
    """

    ABSTRACT = "Abstract"
    METHODS = "Methods"
    SERIES_INFORMATION = "SeriesInformation"
    TABLE_OF_CONTENTS = "TableOfContents"
    TECHNICAL_INFO = "TechnicalInfo"
    OTHER = "Other"


class Description(BaseModel):
    """
    All additional information that does not fit in any of the other categories.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    description: str
    """
    All additional information that does not fit in any of the other categories.
    """
    description_type: Annotated[DescriptionType, Field(alias="descriptionType")]
    """
    The type of the Description.
    """


class GeoLocationPoint(BaseModel):
    """
    A point location in space.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    point_longitude: Annotated[float, Field(alias="pointLongitude")]
    """
    Longitudinal dimension of point.
    """
    point_latitude: Annotated[float, Field(alias="pointLatitude")]
    """
    Latitudinal dimension of point.
    """


class GeoLocationBox(BaseModel):
    """
    The spatial limits of a box.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    west_bound_longitude: Annotated[float, Field(alias="westBoundLongitude")]
    """
    Western longitudinal dimension of box.
    """
    east_bound_longitude: Annotated[float, Field(alias="eastBoundLongitude")]
    """
    Eastern longitudinal dimension of box.
    """
    south_bound_latitude: Annotated[float, Field(alias="southBoundLatitude")]
    """
    Southern latitudinal dimension of box.
    """
    north_bound_latitude: Annotated[float, Field(alias="northBoundLatitude")]
    """
    Northern latitudinal dimension of box.
    """


class GeoLocationPolygon(BaseModel):
    """
    A drawn polygon area, defined by a set of points and lines connecting the points in a closed chain.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    polygon_point: Annotated[GeoLocationPoint | None, Field(alias="polygonPoint")] = None
    in_polygon_point: Annotated[GeoLocationPoint | None, Field(alias="inPolygonPoint")] = None


class GeoLocation(BaseModel):
    """
    Spatial region or named place where the data was gathered or about which the data is focused.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    geo_location_point: Annotated[GeoLocationPoint | None, Field(alias="geoLocationPoint")] = None
    geo_location_box: Annotated[GeoLocationBox | None, Field(alias="geoLocationBox")] = None
    geo_location_place: Annotated[str | None, Field(alias="geoLocationPlace")] = None
    """
    Description of a geographic location.
    """
    geo_location_polygon: Annotated[
        list[GeoLocationPolygon] | None, Field(alias="geoLocationPolygon", min_length=4)
    ] = None


class FunderIdentifierType(Enum):
    """
    The type of the funderIdentifier.
    """

    CROSSREF_FUNDER_ID = "Crossref Funder ID"
    GRID = "GRID"
    ISNI = "ISNI"
    ROR = "ROR"
    OTHER = "Other"


class FundingReference(BaseModel):
    """
    Information about financial support (funding) for the resource being registered.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    funder_name: Annotated[str, Field(alias="funderName")]
    """
    Name of the funding provider.
    """
    funder_identifier: Annotated[str | None, Field(alias="funderIdentifier")] = None
    """
    Uniquely identifies a funding entity, according to various types
    """
    funder_identifier_type: Annotated[FunderIdentifierType, Field(alias="funderIdentifierType")]
    """
    The type of the funderIdentifier.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the funder identifier scheme.
    """
    award_number: Annotated[str | None, Field(alias="awardNumber")] = None
    """
    The code assigned by the funder to a sponsored award (grant).
    """
    award_uri: Annotated[AnyUrl | None, Field(alias="awardURI")] = None
    """
    The URI leading to a page provided by the funder for more information about the award (grant).
    """
    award_title: Annotated[str | None, Field(alias="awardTitle")] = None
    """
    The human readable title or name of the award (grant).
    """


class RelatedItemIdentifier(BaseModel):
    """
    The identifier for the related item.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    related_item_identifier_type: Annotated[
        RelatedIdentifierType | None, Field(alias="relatedItemIdentifierType")
    ] = None
    related_metadata_scheme: Annotated[str | None, Field(alias="relatedMetadataScheme")] = None
    """
    The name of the schemes.
    """
    scheme_uri: Annotated[AnyUrl | None, Field(alias="schemeURI")] = None
    """
    The URI of the name identifier scheme.
    """
    scheme_type: Annotated[str | None, Field(alias="schemeType")] = None
    """
    The type of the relatedMetadataScheme, linked with the schemeURI
    """


class RelatedItemCreator(BaseModel):
    """
    The institution or person responsible for creating the related resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str
    """
    The full name of the related item creator
    """
    name_type: Annotated[NameType | None, Field(alias="nameType")] = None
    given_name: Annotated[str | None, Field(alias="givenName")] = None
    """
    The personal or first name of the creator.
    """
    family_name: Annotated[str | None, Field(alias="familyName")] = None
    """
    The surname or last name of the creator.
    """


class RelatedItemTitle(BaseModel):
    """
    Title of the related item.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    title: str
    """
    Title of the related item.
    """
    title_type: Annotated[str | None, Field(alias="titleType")] = None
    """
    Type of the related item title.
    """


class RelatedItemContributor(RelatedItemCreator):
    """
    An institution or person identified as contributing to the development of the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    contributor_type: Annotated[ContributorType, Field(alias="contributorType")]


class NumberType(Enum):
    """
    Type of the related item's number, e.g., report number or article number.
    """

    ARTICLE = "Article"
    CHAPTER = "Chapter"
    REPORT = "Report"
    OTHER = "Other"


class PublicationYear1(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}$")]
    """
    The year when the data was or will be made publicly available.
    """


class Event(Enum):
    """
    Indicates a state-change action for the DOI
    """

    PUBLISH = "publish"
    REGISTER = "register"
    HIDE = "hide"


class RelatedItem(BaseModel):
    """
    Information about a resource related to the one being registered.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    related_item_type: Annotated[ResourceTypeGeneral, Field(alias="relatedItemType")]
    relation_type: Annotated[ResourceTypeGeneral, Field(alias="relationType")]
    related_item_identifier: Annotated[
        RelatedItemIdentifier | None, Field(alias="relatedItemIdentifier")
    ] = None
    creators: list[RelatedItemCreator] | None = None
    """
    The institution or person responsible for creating the related resource.
    """
    titles: Annotated[list[RelatedItemTitle], Field(min_length=1)]
    """
    Title of the related item
    """
    publication_year: Annotated[int | PublicationYear1 | None, Field(alias="publicationYear")] = (
        None
    )
    """
    The year when the data was or will be made publicly available.
    """
    volume: str | None = None
    """
    Volume of the related item.
    """
    issue: str | None = None
    """
    Issue number or name of the related item.
    """
    number: str | None = None
    """
    Number of the resource within the related item, e.g., report number or article number.
    """
    number_type: Annotated[NumberType | None, Field(alias="numberType")] = None
    """
    Type of the related item's number, e.g., report number or article number.
    """
    first_page: Annotated[str | None, Field(alias="firstPage")] = None
    """
    First page of the resource within the related item, e.g., of the chapter, article, or conference paper in proceedings.
    """
    last_page: Annotated[str | None, Field(alias="lastPage")] = None
    """
    Last page of the resource within the related item, e.g., of the chapter, article, or conference paper in proceedings.
    """
    publisher: str | None = None
    """
    The name of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the resource.
    """
    edition: str | None = None
    """
    Edition or version of the related item.
    """
    contributors: list[RelatedItemContributor] | None = None
    """
    An institution or person identified as contributing to the development of the resource
    """


class DataCiteAttributes(BaseModel):
    """
    DataCite Metadata Schema
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    doi: str | None = None
    """
    The full DOI (prefix + suffix)
    """
    prefix: str | None = None
    """
    The namespace prefix
    """
    suffix: str | None = None
    """
    The suffix portion of the DOI
    """
    event: Event | None = None
    """
    Indicates a state-change action for the DOI
    """
    identifiers: list[Identifier]
    creators: Annotated[list[Creator], Field(min_length=1)]
    """
    The main researchers involved in producing the data, or the authors of the publication, in priority order.
    """
    titles: Annotated[list[Title], Field(min_length=1)]
    """
    Names or titles by which a resource is known. May be the title of a dataset or the name of a piece of software or an instrument.
    """
    publisher: Publisher
    publication_year: Annotated[int | PublicationYear1, Field(alias="publicationYear")]
    """
    The year when the data was or will be made publicly available.
    """
    subjects: list[Subject] | None = None
    """
    Subjects, keywords, classification codes, or key phrases describing the resource.
    """
    contributors: list[Contributor] | None = None
    """
    The institution or person responsible for collecting, managing, distributing, or otherwise contributing to the development of the resource.
    """
    dates: list[Date] | None = None
    """
    Different dates relevant to the work.
    """
    language: str | None = None
    """
    The primary language of the resource
    """
    types: ResourceType
    alternate_identifiers: Annotated[
        list[AlternateIdentifier] | None, Field(alias="alternateIdentifiers")
    ] = None
    """
    An identifier other than the primary Identifier applied to the resource being registered.
    """
    related_identifiers: Annotated[
        list[RelatedIdentifier] | None, Field(alias="relatedIdentifiers")
    ] = None
    """
    Identifiers of related resources.
    """
    sizes: list[str] | None = None
    """
    Size (e.g., bytes, pages, inches, etc.) or duration (extent), e.g., hours, minutes, days, etc., of a resource.
    """
    formats: list[str] | None = None
    """
    Technical format of the resources.
    """
    version: str | None = None
    """
    The version number of the resources.
    """
    rights_list: Annotated[list[Right] | None, Field(alias="rightsList")] = None
    """
    Any rights information for this resource
    """
    descriptions: list[Description] | None = None
    geo_locations: Annotated[list[GeoLocation] | None, Field(alias="geoLocations")] = None
    """
    Spatial regions or named places where the data was gathered or about which the data is focused.
    """
    funding_references: Annotated[
        list[FundingReference] | None, Field(alias="fundingReferences")
    ] = None
    """
    Information about financial support (funding) for the resource being registered.
    """
    related_items: Annotated[list[RelatedItem] | None, Field(alias="relatedItems")] = None
    """
    Informations about a resource related to the one being registered.
    """


class Data(BaseModel):
    """
    TODO
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    type: str = "dois"
    attributes: DataCiteAttributes | None = None


class DataCiteMetadata46(BaseModel):
    """
    DataCite Metadata Schema
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    data: Data


class Model(RootModel[DataCiteMetadata46]):
    root: DataCiteMetadata46
